import {CuePrinter} from './CuePrinter';
import {readFile} from 'TestUtils';

describe('CuePrinter', () => {

  it('should print exactly the same cuesheet as parsed', () => {
    const cueData = readFile('samples/MusicBrainz/cues/Norah Jones.cue');
    const cue = CueParser.parse(cueData, {
      autoCreateFile: true
    });

    const out = CuePrinter.print(cue);
    const outCue = CueParser.parse(out, {
      autoCreateFile: true
    });
    expect(outCue).toEqual(cue);
  });

  it('should not duplicate generated by comment (#85)', () => {
    const cueData = readFile('samples/MusicBrainz/cues/Norah Jones.cue');
    const cue = CueParser.parse(cueData, {
      autoCreateFile: true
    });
    const initRems = cue.rem.length;

    // Création du commentaire generated by
    const out = CuePrinter.print(cue);
    const outCue = CueParser.parse(out, {
      autoCreateFile: true
    });
    expect(outCue.rem.length).toEqual(initRems + 1);

    // Modification du commentaire generated by
    const out2 = CuePrinter.print(outCue);
    const outCue2 = CueParser.parse(out2, {
      autoCreateFile: true
    });
    // console.log(outCue2.rem);
    expect(outCue2.rem.length).toEqual(outCue.rem.length);
  });

});
